export class Colors {
  static THEMES: string[] = [
    'white',
    'yellow',
    'pink',
    'green',
    'dark',
    'whiteSky',
    'darkSky'
  ];

  static THEME_COLOR: Record<string, string> = {
    'white': '#FFFFFF',
    'yellow': '#BD9063',
    'pink': '#FFE4E5',
    'green': '#C5E7CE',
    'dark': '#202224',
    'whiteSky': '#FFFFFF',
    'darkSky': '#202224'
  }

  static THEME_BORDER_COLOR: Record<string, string> = {
    'white': '#D1D1D1',
    'yellow': '#A06D4D',
    'pink': '#E3B4B8',
    'green': '#A3D2B8',
    'dark': '#4A4A4A',
    'whiteSky': '#D1D1D1',
    'darkSky': '#4A4A4A'
  }

}